src/Entity/OcPatients.php
<?php

namespace App\Entity;

use App\Repository\OcPatientsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OcPatientsRepository::class)
 */
class OcPatients
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $matricule;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $gender;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthday;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $profession;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $hobbies;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ice_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ice_phone;

    /**
     * @ORM\OneToMany(targetEntity=OcPatientParameters::class, mappedBy="patient")
     */
    private $parameters;

    /**
     * @ORM\OneToMany(targetEntity=OcConsultation::class, mappedBy="patient")
     */
    private $consultations;

    public function __construct()
    {
        $this->parameters = new ArrayCollection();
        $this->consultations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMatricule(): ?string
    {
        return $this->matricule;
    }

    public function setMatricule(string $matricule): self
    {
        $this->matricule = $matricule;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(?\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getProfession(): ?string
    {
        return $this->profession;
    }

    public function setProfession(?string $profession): self
    {
        $this->profession = $profession;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getHobbies(): ?string
    {
        return $this->hobbies;
    }

    public function setHobbies(?string $hobbies): self
    {
        $this->hobbies = $hobbies;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getIceName(): ?string
    {
        return $this->ice_name;
    }

    public function setIceName(?string $ice_name): self
    {
        $this->ice_name = $ice_name;

        return $this;
    }

    public function getIcePhone(): ?string
    {
        return $this->ice_phone;
    }

    public function setIcePhone(?string $ice_phone): self
    {
        $this->ice_phone = $ice_phone;

        return $this;
    }

    /**
     * @return Collection<int, OcPatientParameters>
     */
    public function getParameters(): Collection
    {
        return $this->parameters;
    }

    public function addParameter(OcPatientParameters $parameter): self
    {
        if (!$this->parameters->contains($parameter)) {
            $this->parameters[] = $parameter;
            $parameter->setPatient($this);
        }

        return $this;
    }

    public function removeParameter(OcPatientParameters $parameter): self
    {
        if ($this->parameters->removeElement($parameter)) {
            // set the owning side to null (unless already changed)
            if ($parameter->getPatient() === $this) {
                $parameter->setPatient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, OcConsultation>
     */
    public function getConsultations(): Collection
    {
        return $this->consultations;
    }

    public function addConsultation(OcConsultation $consultation): self
    {
        if (!$this->consultations->contains($consultation)) {
            $this->consultations[] = $consultation;
            $consultation->setPatient($this);
        }

        return $this;
    }

    public function removeConsultation(OcConsultation $consultation): self
    {
        if ($this->consultations->removeElement($consultation)) {
            // set the owning side to null (unless already changed)
            if ($consultation->getPatient() === $this) {
                $consultation->setPatient(null);
            }
        }

        return $this;
    }
}

src/Form/OcPatientsType.php
<?php

namespace App\Form;

use App\Entity\OcPatients;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OcPatientsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('matricule')
            ->add('name')
            ->add('lastName')
            ->add('gender')
            ->add('birthday')
            ->add('phone')
            ->add('profession')
            ->add('email')
            ->add('location')
            ->add('hobbies')
            ->add('picture')
            ->add('ice_name')
            ->add('ice_phone')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => OcPatients::class,
        ]);
    }
}

src/Controller/OcPatientsController.php
<?php

namespace App\Controller;

use App\Entity\OcPatients;
use App\Form\OcPatientsType;
use App\Repository\OcPatientsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/patients")
 */
class OcPatientsController extends AbstractController
{
    /**
     * @Route("/", name="app_oc_patients_index", methods={"GET"})
     */
    public function index(OcPatientsRepository $ocPatientsRepository): Response
    {
        return $this->render('oc_patients/index.html.twig', [
            'oc_patients' => $ocPatientsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_oc_patients_new", methods={"GET", "POST"})
     */
    public function new(Request $request, OcPatientsRepository $ocPatientsRepository): Response
    {
        $ocPatient = new OcPatients();
        $form = $this->createForm(OcPatientsType::class, $ocPatient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ocPatientsRepository->add($ocPatient, true);

            return $this->redirectToRoute('app_oc_patients_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('oc_patients/new.html.twig', [
            'oc_patient' => $ocPatient,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_oc_patients_show", methods={"GET"})
     */
    public function show(OcPatients $ocPatient): Response
    {
        return $this->render('oc_patients/show.html.twig', [
            'oc_patient' => $ocPatient,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_oc_patients_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, OcPatients $ocPatient, OcPatientsRepository $ocPatientsRepository): Response
    {
        $form = $this->createForm(OcPatientsType::class, $ocPatient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ocPatientsRepository->add($ocPatient, true);

            return $this->redirectToRoute('app_oc_patients_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('oc_patients/edit.html.twig', [
            'oc_patient' => $ocPatient,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_oc_patients_delete", methods={"POST"})
     */
    public function delete(Request $request, OcPatients $ocPatient, OcPatientsRepository $ocPatientsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ocPatient->getId(), $request->request->get('_token'))) {
            $ocPatientsRepository->remove($ocPatient, true);
        }

        return $this->redirectToRoute('app_oc_patients_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/oc_patients/_delete_form.html.twig
<form method="post" action="{{ path('app_oc_patients_delete', {'id': oc_patient.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ oc_patient.id) }}">
    <button class="btn">Delete</button>
</form>

templates/oc_patients/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit OcPatients{% endblock %}

{% block body %}
    <h1>Edit OcPatients</h1>

    {{ include('oc_patients/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_oc_patients_index') }}">back to list</a>

    {{ include('oc_patients/_delete_form.html.twig') }}
{% endblock %}

templates/oc_patients/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Patients
{% endblock %}

{% block body %}
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1>Patients</h1>
				</div>
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item">
							<a href="{{ path('app_oc_dashboard') }}">Accueil</a>
						</li>
						<li class="breadcrumb-item active">Patients</li>
					</ol>
				</div>
			</div>
		</div>
		<!-- /.container-fluid -->
	</section>

	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-12">
					<div class="card">
						<div class="card-header">
							<h3 class="card-title">Liste des patients</h3>
						</div>
						<!-- /.card-header -->
						<div class="card-body">
							<table id="example1" class="table table-bordered table-striped">
								<thead>
									<tr>
										<th>Matricule</th>
										<th>Noms</th>
										<th>Phone</th>
										<th>Email</th>
										<th>Profession</th>
										<th>Quartier</th>
										<th>Actions</th>
									</tr>
								</thead>
								<tbody>
									{% for oc_patient in oc_patients %}
										<tr>
											<td>{{ oc_patient.matricule }}</td>
											<td>{{ oc_patient.name }}</td>
											<td>{{ oc_patient.phone }}</td>
											<td>{{ oc_patient.email }}</td>
											<td>{{ oc_patient.profession }}</td>
											<td>{{ oc_patient.location }}</td>
											<td>
												<a class="btn btn-warning btn-sm" href="{{ path('app_oc_patients_show', {'id': oc_patient.id}) }}">
													<i class="fas fa-eye"></i>
												</a>
												<a class="btn btn-info btn-sm" href="{{ path('app_oc_patients_edit', {'id': oc_patient.id}) }}">
													<i class="fas fa-pencil-alt"></i>
												</a>
											</td>
										</tr>
									{% else %}
										<tr>
											<td colspan="5">Aucun éléments trouvés</td>
										</tr>
									{% endfor %}
								</tbody>
								<tfoot>
									<tr>
										<th>Matricule</th>
										<th>Noms</th>
										<th>Phone</th>
										<th>Email</th>
										<th>Profession</th>
										<th>Quartier</th>
										<th>Actions</th>
									</tr>
								</tfoot>
							</table>
						</div>
						<!-- /.card-body -->
					</div>
					<!-- /.card -->
					<a class="btn btn-primary float-right" href="{{ path('app_oc_patients_new') }}">
						<i class="fas fa-plus"></i>
						Ajouter patient
					</a>
				</div>
				<!-- /.col -->
			</div>
			<!-- /.row -->
		</div>
		<!-- /.container-fluid -->
	</section>
	<!-- /.content -->
{% endblock %}

templates/oc_patients/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New OcPatients{% endblock %}

{% block body %}
    <h1>Create new OcPatients</h1>

    {{ include('oc_patients/_form.html.twig') }}

    <a href="{{ path('app_oc_patients_index') }}">back to list</a>
{% endblock %}

templates/oc_patients/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}OcPatients{% endblock %}

{% block body %}
    <h1>OcPatients</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ oc_patient.id }}</td>
            </tr>
            <tr>
                <th>Matricule</th>
                <td>{{ oc_patient.matricule }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ oc_patient.name }}</td>
            </tr>
            <tr>
                <th>LastName</th>
                <td>{{ oc_patient.lastName }}</td>
            </tr>
            <tr>
                <th>Gender</th>
                <td>{{ oc_patient.gender }}</td>
            </tr>
            <tr>
                <th>Birthday</th>
                <td>{{ oc_patient.birthday ? oc_patient.birthday|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ oc_patient.phone }}</td>
            </tr>
            <tr>
                <th>Profession</th>
                <td>{{ oc_patient.profession }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ oc_patient.email }}</td>
            </tr>
            <tr>
                <th>Location</th>
                <td>{{ oc_patient.location }}</td>
            </tr>
            <tr>
                <th>Hobbies</th>
                <td>{{ oc_patient.hobbies }}</td>
            </tr>
            <tr>
                <th>Picture</th>
                <td>{{ oc_patient.picture }}</td>
            </tr>
            <tr>
                <th>Ice_name</th>
                <td>{{ oc_patient.iceName }}</td>
            </tr>
            <tr>
                <th>Ice_phone</th>
                <td>{{ oc_patient.icePhone }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_oc_patients_index') }}">back to list</a>

    <a href="{{ path('app_oc_patients_edit', {'id': oc_patient.id}) }}">edit</a>

    {{ include('oc_patients/_delete_form.html.twig') }}
{% endblock %}